vim.cmd([[ set number ]])
vim.cmd([[ set inccommand=split ]])
vim.cmd([[ set encoding=utf8 ]])
vim.cmd([[ set mouse=a ]])
vim.cmd([[ set confirm ]])
vim.cmd([[ set title ]])
vim.cmd([[ set t_Co=256 ]])
vim.cmd([[ set expandtab]])
vim.cmd([[ set tabstop=4 ]])
vim.cmd([[ set shiftwidth=4 ]])
vim.cmd([[ set softtabstop=2 ]])
vim.cmd([[ set softtabstop=2 ]])
vim.cmd([[ set guicursor= ]])
vim.cmd([[ syntax on]])
vim.cmd([[colorscheme catppuccin-mocha]])
